### ISSUE TITLE
ddev setup command seems incomplete

### ISSUE THREAD

**Issue by maddy2101** [TYPO3/get.typo3.org#230]
When running the command sequence for ddev setup a v10 instance, I end up with 

```
$ ddev typo3cms install:setup

Welcome to the TYPO3 Console installer!

➤ Prepare installation
✔ Ok
➤ Check environment and create folders
✔ Ok
➤ Set up database connection
✔ Skipped Set up database connection
➤ Select database
✔ Skipped Select database
➤ Set up database


  [ Symfony\Component\Console\Exception\RuntimeException ]
  Option "--admin-user-name" is not set, but is required and user interaction
   is disabled
...
Failed to run typo3cms install:setup: exit status 255
```
The install command, that gives me the error, needs more parameters given from the start. Also some explanation about the password required and some ways to fix an aborted install (there is no going back, only deleting everything and starting over) would be helpful.

I am ready to contribute here, but I need a hand about the best practice how to actually set up an instance.

**Comment by gilbertsoft** [comment]
The issue here is the usage of Git Bash which requires to prepend `winpty` before each interactive command, in this case `winpty ddev typo3cms install:setup` will solve the issue.

We have to provide some additional information to the users, maybe a FAQ page. Also a how to reset a project is a important info.
