### ISSUE TITLE
Add hint about config.yaml

### ISSUE THREAD

**Issue by franzholz** [TYPO3/get.typo3.org#253]
The page 
https://get.typo3.org/version/9
recommends 4 lines to execute in a command shell.

```
ddev config --project-type=typo3 --docroot=public --create-docroot
ddev composer create "typo3/cms-base-distribution:^9.5"
ddev typo3cms install:setup
ddev launch

```

However this assumes, that the ports 80 and 443 will be available. Unfortunately in most cases there is already an apache on the server which uses them.

Therefore it is necessary to tell the users that they must immediately edit the config.yaml in this or a similar manner:

```
router_http_port: "8080"
router_https_port: "8443"

```

**Comment by gilbertsoft** [comment]
It's not the job of the download portal here to provide detailed information about the usage of DDEV. There is a link provided to the DDEV Docs which really should be fine. We cover here a normal operation without any webserver installed which is just fine for 95% of the people.

And please check the ddev config command which has options to also provide these ports within the first line, no need to edit the config.yaml. And maybe it's better to provide these ports at the global configuration instead of the project's one because normally you like to have settings which works everywhere. Special settings should be applied by the global configuration see https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/#global_configyaml-options. Currently it looks like the ports are not part of the global config or missing in the docs. See also https://github.com/drud/ddev/issues/3240

**Comment by franzholz** [comment]
From where do you have this number, that 95% of the TYPO3 users do not have a webserver installed?
Thank you for the info about a "ddev config" command. I have never read about this.

It would be best if your valuable information could be provided on a place where it can easily be found.

**Comment by gilbertsoft** [comment]
> From where do you have this number, that 95% of the TYPO3 users do not have a webserver installed?

I'm actively giving support for DDEV and TYPO3 for about 3 years. So I know what people are asking for.

> It would be best if your valuable information could be provided on a place where it can easily be found.

There is a hint on the home page of the DDEV docs see https://ddev.readthedocs.io/en/latest/#using-ddev-alongside-other-development-environments

**Comment by franzholz** [comment]
However the documentation does not allow to set the ports for the file `$HOME/.ddev/global_config.yaml `, because they are not listed as available options for it.
 

- host_https_port
- host_webserver_port
- router_http_port,
- router_https_port

**Comment by gilbertsoft** [comment]
I'm going to close this issue now as it's out of scope. As already said it's not the job of the download portal to provide configuration details for all cases but the upstream which is linked. If there's something missing in the upstream docs please file an issue there instead.
