### ISSUE TITLE
Bug, if --docroot=public is set to some other value

### ISSUE THREAD

**Issue by marble** [TYPO3/get.typo3.org#291]
### Use case

I'm trying [this recipe](https://get.typo3.org/version/10#version-download):
![grafik](https://user-images.githubusercontent.com/307057/157518393-42a432cd-d7d5-4f26-94d0-2f8cb272f48d.png)

### Problem

IMHO this code suggests, that it should be possible to use `--docroot=public_html` just as well. However, with a value different from `public` the recipe silently fails with some strange behaviour. Or, to say at least, some input is asked for that the newbie doesn't have.

### Suggested solutions

1. Point out in a comment line, that the value must not be changed
2. Better would be: Include a check, that `docroot` is set to an expected value.
3. Best would be: Make the recipe handle ANY valid name.

**Comment by gilbertsoft** [comment]
This option only changes the docroot (webserver configuration of DDEV) but does not tell composer to also use it. This you have to change in your `composer.json` see https://github.com/TYPO3/CmsComposerInstallers#web-dir.

Try it with this snippet instead:

```
ddev config --project-type=typo3 --docroot=public_html --create-docroot
ddev composer create "typo3/cms-base-distribution:^11.5"  --no-install
ddev composer config extra.typo3/cms.web-dir public_html
ddev composer install
ddev typo3cms install:setup
ddev launch
```

**Comment by marble** [comment]
Oh, great, that's something I was looking for. I ran into another problem when I added `--xdebug=true`. Will try again tomorrow!

**Comment by marble** [comment]
### Still problematic
Things look very fragile to me, as soon as I try "to specify something".

### So this does work:
<pre> # Create ~/ddevprojects/dummy/project

true \
   &&  mkdir -p ~/ddevprojects/dummy/project \
   &&  cd ~/ddevprojects/dummy/project \
   &&  ddev config \
       --create-docroot \
       --docroot=public \
       --http-port=8072 \
       --https-port=44372 \
       --php-version="7.4" \
       --project-type=typo3 \
       --xdebug-enabled=false \
   &&  ddev composer create "typo3/cms-base-distribution:^10.4"  \
   &&  ddev composer config "extra.typo3/cms.web-dir" public \
   &&  ddev composer install \
   &&  ddev typo3cms install:setup \
   &&  ddev launch
</pre>

And this is how I remove the project again:
<pre>
# Remove ~/ddevprojects/dummy/project

true \
   &&  ddev poweroff \
   &&  cd ~/ddevprojects/dummy/project  \
   &&  ddev delete --omit-snapshot --yes \
   &&  cd ~/ddevprojects/dummy/  \
   &&  rm -rf ~/ddevprojects/dummy/project
</pre>

### Problem
However, when I replace `public` with `public_html` in the above, the script starts asking about Database specification - which it shouldn't do. And it doesn't help to have `--no-install` in the `ddev composer create ...` line.

**Comment by gilbertsoft** [comment]
We are getting more and more off topic now, this repo is about the download portal and not to answer questions like this. As you already asked in Slack in the meantime, I'm goning to close this issue.

For DDEV related questions please sign in to the DDEV Discord instead, thanks! See https://github.com/drud/ddev/issues/new/choose

**Comment by marble** [comment]
Well, returning to get.typo3.org: If the above recipe is the most recommended one and the first one mentioned, it should be clear and minimal robust. And it will easily lead - especially developers - into problems, as they will assume, that ⓐ `--docroot` MUST be specified, but ⓑ from developer knowledge they will also assume, that some other value can be used as well. And that is not the case.

IMHO either:
① Change the text line above to "In a new project folder using your favorite shell, run **exactly** these lines:"
② Or: Add the hint, that `--docroot=public` must not be changed (Since I still couldn't find a way to make the recipe work with a different value).

That's why I opened the ticket on https://github.com/TYPO3/get.typo3.org

**Comment by gilbertsoft** [comment]
Sorry, there is no reason to change this folder at all, not sure why you think you have to change it. It's the default configuration recommended from the core. Nobody ever had a problem with this recipe since I added it two or three years ago. If you start to change a recipe you first should understand what you are doing and what the single pieces are for and in this case you did not read the documentation of the `typo3/cms-composer-installers` which you try to change.

Lets have a look at the [installation guide](https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Installation/Install.html#execute-composer-create-project), here it's clearly stated which folder structure will be created. There is no hint on how to change this structure for a good reason even if the `typo3/cms-composer-installers` has the feature to do it. We remove more and more of these features with every version of the installer also for good reasons but which is out of scope here.

I'm really happy to improove things but changing the public folder is really out of scope as it's a very advanced feature which even if I know about I never had the idea to use it. Instead, the webserver configuration should be adjusted and that is exactly what the option `--docroot=public` does, it lets ddev know which folder has to be configured as the webserver's docroot. And that's exactly what you will do in the production environment afterwards.

**Comment by marble** [comment]
In this ticket I'm not asking about help about the installation procedure. Howerever, it is YOU who is giving explanations about it and then say it's off topic.

Instead, I'm providing the feedback, that THE TEXT, including the code snippet, on get.typo3.org is misleading. It SUGGESTS, that docroot is a value that could vary.

I proposed some solutions - you didn't give an answer on that. Please read again in the above: ① Either TELL people, that they MUST NOT change that value, or ② drop the parameter from the recipe or ③ include a check and abort the install with a clear message.

Why? Because we want to make sure that the very first installation recipe on the download page of get.typo3.org DOES work.
