### ISSUE TITLE
BUG: Clear caches for endpoints after release

### ISSUE THREAD

**Issue by NeoBlack** [TYPO3/get.typo3.org#374]
We experienced the problem that after a release is public, the endpoints of the API deliver are not the latest version.
We have to use the clear cache endpoint to clear the cache for each version before the endpoints deliver the correct latest version.

**Comment by gilbertsoft** [comment]
I guess you are talking about an ELTS release and it was released using Darth?

**Comment by NeoBlack** [comment]
Yes, in our case, it is ELTS, but I don't understand your question.

**Comment by gilbertsoft** [comment]
Well, Darth clears the cache during the release cycle which should be fine and sufficient. That's why I'm asking. Need to reproduce your issue somehow, we did not have issues with the LTS releases during the last two months.

**Comment by andreaskienast** [comment]
Due to some special needs, we're posting releases manually to the `/api/v1/release` endpoint. While _some_ caches seemed to be cleared as indicated by updated version numbers on the front page of get.typo3.org, `/api/v1/major/{version}/release` apparently delivered outdated results, making API calls to `/api/v1/cache/*/{version}` mandatory.

I don't know if Darth calls the cache-related endpoints in a process we have to skip, which shouldn't be necessary in any case anyway.

**Comment by gilbertsoft** [comment]
Fully agree that caches should get cleared automatically if needed. Discussed this with Benji in June and his argumentation was, cache clearing should occur only once after the release cycle. But this isn't the case for Darth, Darth clears the cache after each release so I'd say this could be changed anyway without drawbacks.

FYI, Darth calls `/api/v1/cache/release/{version}` see https://github.com/TYPO3/darth/blob/main/conf/release.yaml#L117 and https://github.com/TYPO3/darth/blob/4fa2d7600f21857d386d01438fc0f981267a2350/src/Service/AnnounceApiService.php#L84 after each release which was tested and looks to work fine. So for the moment please call this endpoint after pushing a release until I fixed it.

**Comment by ohader** [comment]
@andreaskienast I guess this issue has been resolved, hasn't it?

**Comment by ohader** [comment]
Yepp, it's resolved 😄
